# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.5"
manifest_format = "2.0"
project_hash = "a4f1c439dfbcba6182af591d029698c37b6cd4e0"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"
version = "1.11.0"

[[deps.ReadWriteFind]]
path = "/Users/crismoen/.julia/dev/ReadWriteFind"
uuid = "6e1ff3fe-52ba-4718-9baa-43b124cc059a"
version = "0.1.0"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"
